import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

module.exports = {
  helpSidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // generates sidebar from /docs-help/
    },
  ],
};
