import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebarsBooks: SidebarsConfig = {
  booksSidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // This should point to root of /docs/product
    },
  ],
};

export default sidebarsBooks;
