import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebarsDatasheets: SidebarsConfig = {
  datasheetsSidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // This should point to root of /docs/product
    },
  ],
};

export default sidebarsDatasheets;
