import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebarsProduct: SidebarsConfig = {
  productSidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // This should point to root of /docs/product
    },
  ],
};

export default sidebarsProduct;
