import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebarsGuide: SidebarsConfig = {
  guideSidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // This should point to root of /docs/product
    },
  ],
};

export default sidebarsGuide;
